- hosts: "{{ host }}"
  gather_facts: yes
  tasks:

    - name: "Update and Upgrade apt packages as sudo on {{ host }}"
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: "Install strongswan-starter package via apt as sudo on {{ host }}"
      become: yes
      apt:
        name: strongswan-starter
        state: present

    - name: "Install unattended-upgrades package via apt as sudo on {{ host }}"
      become: yes
      apt:
        name: unattended-upgrades
        state: present

    - name: "Configure unattended-upgrades package via apt as sudo on {{ host }}"
      become: yes
      template:
        src: "../../playbook-files/unattended-upgrades/50unattended-upgrades"
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
        owner: root
        group: root
        mode: 0644

    - name: "Create `/usr/local/share/cloud-conductor` directory"
      become: yes
      file:
        path: "/usr/local/share/cloud-conductor"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: "Create `/usr/local/share/cloud-conductor/scripts` directory"
      become: yes
      file:
        path: "/usr/local/share/cloud-conductor/scripts"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: "Copy `iptables-persistent.sh` script from playbook-files to `/usr/local/share/cloud-conductor/scripts/iptables-persistent.sh`"
      become: true
      template:
        src: "../../playbook-files/jump-host/iptables-persistent.sh"
        dest: "/usr/local/share/cloud-conductor/scripts/iptables-persistent.sh"
        owner: root
        group: root
        mode: 0644

    - name: "Create cronjob `iptables-persistent` at reboot"
      become: true
      ansible.builtin.cron:
        name: "iptables-persistent"
        special_time: reboot
        job: "sh /usr/local/share/cloud-conductor/scripts/iptables-persistent.sh"
        state: present

    - name: "Execute iptables-persistent.sh script"
      become: yes
      shell: "sh /usr/local/share/cloud-conductor/scripts/iptables-persistent.sh"

    - name: "Restart systemd-networkd"
      become: true
      shell: "systemctl restart systemd-networkd"
      register: systemd_networkd_restart

    - name: "Remove all but the first line which includes PasswordAuthentication from sshd_config"
      become: yes
      replace:
        path: "/etc/ssh/sshd_config"
        after: "PasswordAuthentication"
        regexp: "^(.*)PasswordAuthentication(.*)$"
        replace: ""

    - name: "Replace the first line which includes PasswordAuthentication from sshd_config"
      become: yes
      replace:
        path: "/etc/ssh/sshd_config"
        regexp: "^(.*)PasswordAuthentication(.*)$"
        replace: "PasswordAuthentication no"

    - name: "Restart ssh"
      become: yes
      service:
        name: ssh
        state: restarted
