# Version of the Docker Compose file format
version: "3"

services:
  # define service
  reverse-proxy:
    # container name
    container_name: reverse-proxy
    # use nginx reverse proxy image
    image: nginxproxy/nginx-proxy:alpine
    # restart container unless stopped to prevent downtimes
    restart: unless-stopped
    # map http and https ports
    ports:
      - "80:80"
      - "443:443"
    # network to be shared between reverse proxy and containers
    networks:
      - container-network
    # volumes needed for reverse proxy configuration, v-hosts and certificates
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # docker socket
      - nginx-conf:/etc/nginx/conf.d # nginx configuration
      - nginx-vhost:/etc/nginx/vhost.d # nginx v-hosts
      - html:/usr/share/nginx/html # nginx html
      - certs-acme:/etc/nginx/certs:ro # nginx certificates
      - ./additional.conf:/etc/nginx/conf.d/additional.conf:ro # additional nginx configuration

  # define service
  acme-companion:
    # container name
    container_name: reverse-proxy-acme-companion
    # use nginx acme companion image
    image: nginxproxy/acme-companion
    # restart container unless stopped to prevent downtimes
    restart: unless-stopped
    # environment variables
    environment:
      - DEFAULT_EMAIL={{ acme_default_email | default('') }}
      - ACME_CA_URI={{ acme_ca_uri | default('') }}
      - ZEROSSL_API_KEY={{ acme_zerossl_api_key | default('') }}
    # share volumes from reverse proxy
    volumes_from:
      - reverse-proxy
    # volumes needed for reverse proxy configuration, v-hosts and certificates
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs-acme:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    # depends on reverse proxy to ensure it starts first
    depends_on:
      - reverse-proxy

# define network
networks:
  # the network that will be shared between reverse proxy and containers
  container-network:

# define volumes the containers reverse proxy and acme companion will share
volumes:
  # configuration
  nginx-conf:
  # v-hosts
  nginx-vhost:
  # html
  html:
  # certificates
  certs-acme:
  # acme scripts
  acme:
