- hosts: "{{ host }}"
  gather_facts: no
  tasks:

    - name: "Close tunnels"
      become: true
      shell: "ipsec down {{ item }}"
      loop: "{{ tunnels }}"
      ignore_errors: true

    - name: "Open tunnels"
      become: true
      shell: "ipsec up {{ item }}"
      loop: "{{ tunnels }}"
