- hosts: "{{ host }}"
  gather_facts: no
  tasks:

    - name: "Run command {{ command }} in container {{ container_name }}"
      become: yes
      command: "docker exec {{ container_name }} {{ command }}"
