- hosts: "{{ host }}"
  gather_facts: no
  tasks:

    - name: "Run command `{{ command }}` on `{{ host }}`"
      command: "{{ command }}"
      register: command_result

    - name: "Print result in json format"
      debug:
        msg: "{{ command_result | to_nice_json }}"
