- hosts: "{{ host }}"
  gather_facts: yes
  become: yes
  tasks:

    - name: Create directories for keys
      file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - /etc/ipsec.d/keys

    - name: Generate server private key
      command: "bash -c 'ipsec pki --gen --type rsa --size 4096 --outform pem > /etc/ipsec.d/keys/server.key'"
      args:
        creates: /etc/ipsec.d/keys/server.key

    - name: Generate server public key
      command: "bash -c 'ipsec pki --pub --in /etc/ipsec.d/keys/server.key --type rsa --outform pem > /etc/ipsec.d/keys/server.pub'"
      args:
        creates: /etc/ipsec.d/keys/server.pub

    - name: Ensure permissions on key files
      file:
        path: "{{ item }}"
        mode: '0600'
      loop:
        - /etc/ipsec.d/keys/server.key
        - /etc/ipsec.d/keys/server.pub

    - name: "Update and Upgrade apt packages as sudo on {{ host }}"
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: "Install strongswan-starter package via apt as sudo on {{ host }}"
      apt:
        name: strongswan-starter
        state: present

    - name: "Install strongswan-pki package via apt as sudo on {{ host }}"
      apt:
        name: strongswan-pki
        state: present

    - name: "Ensure required packages for Docker are installed"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: "Download and format Docker's GPG key"
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        chmod 0644 /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: "Set up the Docker repository"
      copy:
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: "Update apt cache with Docker repository"
      apt:
        update_cache: true

    - name: "Install Docker and dependencies"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: "Ensure Docker service is running and enabled"
      service:
        name: docker
        state: started
        enabled: true

    - name: "Install unattended-upgrades package via apt as sudo on {{ host }}"
      apt:
        name: unattended-upgrades
        state: present

    - name: "Configure unattended-upgrades package via apt as sudo on {{ host }}"
      template:
        src: "../../playbook-files/unattended-upgrades/50unattended-upgrades"
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
        owner: root
        group: root
        mode: 0644

    - name: "Create `/usr/local/share/cloud-conductor` directory"
      file:
        path: "/usr/local/share/cloud-conductor"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: "Create `/usr/local/share/cloud-conductor/scripts` directory"
      file:
        path: "/usr/local/share/cloud-conductor/scripts"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: "Remove all but the first line which includes PasswordAuthentication from sshd_config"
      replace:
        path: "/etc/ssh/sshd_config"
        after: "PasswordAuthentication"
        regexp: "^(.*)PasswordAuthentication(.*)$"
        replace: ""

    - name: "Replace the first line which includes PasswordAuthentication from sshd_config"
      replace:
        path: "/etc/ssh/sshd_config"
        regexp: "^(.*)PasswordAuthentication(.*)$"
        replace: "PasswordAuthentication no"

    - name: "Restart ssh"
      service:
        name: ssh
        state: restarted
